### ISSUE TITLE
can't get newest version through composer

### ISSUE THREAD

**Issue by diodac** [isolate-org/framework#3]
shouldn't you add new tag?

**Comment by norberttech** [comment]
https://github.com/isolate-org/framework/releases/tag/1.0.0-alpha2 done

**Comment by diodac** [comment]
should packagist knows about this new tag?

**Comment by norberttech** [comment]
http://prntscr.com/ay8lne ?

**Comment by diodac** [comment]
moment ago it wasn't there and I had to add this repo to "repositories" in composer.json
